blank_issues_enabled: false
contact_links:
  - name: 讨论区 Discussion
    url: https://github.com/RenAhsAcme/Personal_Template_Base/discussions/
    about: 使用中若遇到问题或有新需求，可先在这里求助和征求意见。  If you encounter any problems or have new needs while using it, you can seek help and opinions here first.